#!/bin/bash
set -eu -o pipefail

# cd into the root directory, which is passed in from build-in-docker
cd "$1"

# build the example projects
pushd examples &>/dev/null
./make.sh hal
./make.sh all
popd &>/dev/null
