name: clang-format Check
on: [pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: "13"
          exclude-regex: (one-third-hal/CMSIS|one-third-hal/f0*|one-third-hal/f1*|one-third-hal/f3*|one-third-hal/f4*|one-third-hal/f7*|one-third-hal/h7*)
          fallback-style: "Google" # optional
